server:
  port: 8888
  use-forward-headers: true
  max-http-header-size: 2097152
  context-parameters.isLog4jAutoInitializationDisabled: true
  session:
    timeout: 1800
    cookie:
      secure: false
      http-only: true
    tracking-modes: cookie
  error:
    include-stacktrace: NEVER
  tomcat:
    max-threads: 5
    port-header: X-Forwarded-Port
    protocol-header: X-Forwarded-Proto
    protocol-header-https-value: https
    remote-ip-header: X-FORWARDED-FOR
    uri-encoding: UTF-8
cas:
  locale:
    defaultValue: zh_CN
  server:
    ajp:
      enabled: false
    http:
      enabled: false
    prefix: https://account.aulang.net
  tgc:
    secure: false
  warningCookie:
    secure: false
  logout:
    followServiceRedirects: true
  ticket:
    st:
      timeToKillInSeconds: 20
    tgt:
      timeToKillInSeconds: 28800
    registry:
      redis:
        host: 127.0.0.1
        port: 6379
        timeout: 2000
  authn:
    oauth:
      refreshToken:
        timeToKillInSeconds: 7776000
      accessToken:
        timeToKillInSeconds: 28800
        maxTimeToLiveInSeconds: 2592000
  serviceRegistry:
    initFromJson: true
    startDelay: 20000
    repeatInterval: 600000
captcha:
  kaptcha.border: 'no'
  kaptcha.textproducer.font.color: blue
  kaptcha.textproducer.font.size: '60'
  kaptcha.textproducer.char.length: '4'
  kaptcha.image.width: '200'
  kaptcha.image.height: '80'
spring:
  application:
    name: account
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  mvc:
    locale: zh_CN
  aop:
    auto: true
    proxy-target-class: true
  cloud:
    bus:
      enabled: false
  thymeleaf:
    mode: HTML
    cache: true
    encoding: UTF-8
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/account