server:
  port: 8888
  session:
    timeout: 1800
    tracking-modes: cookie
    cookie:
      secure: true
      http-only: true
  use-forward-headers: true
  tomcat:
    max-threads: 5
    port-header: X-Forwarded-Port
    protocol-header: X-Forwarded-Proto
    protocol-header-https-value: https
    remote-ip-header: X-Forwarded-For
    uri-encoding: UTF-8

spring:
  application:
    name: account
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  aop:
    auto: true
    proxy-target-class: true
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/account

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka/