server:
  port: 8888
  session:
    timeout: 1800
    tracking-modes: cookie
    cookie:
      secure: true
      http-only: true
  use-forward-headers: true
  tomcat:
    max-threads: 5
    port-header: X-Forwarded-Port
    protocol-header: X-Forwarded-Proto
    protocol-header-https-value: https
    remote-ip-header: X-Forwarded-For
    uri-encoding: UTF-8
spring:
  application:
    name: account
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  mvc:
    locale: zh_CN
  aop:
    auto: true
    proxy-target-class: true
  thymeleaf:
    mode: HTML
    cache: true
    encoding: UTF-8
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/account